### ISSUE TITLE
no such file error

### ISSUE THREAD

**Issue by gidden** [elliottbiondo/zo#1]
```
11:21 Kermit:~/work/publications/ans15s [master|…1]$ ls
1k_avg_front_time_fc1_solvercbc.pdf  anstrans.cls                                bibliography.bib             LICENSE   neup_logo_large.jpg  summary.aux  summary.blg  summary.pdf  sys
ans.bst                              base_back_n_rxtr_time_fc1_solvergreedy.pdf  exchange_xlation_timing.pdf  Makefile  README.md            summary.bbl  summary.log  summary.tex
11:21 Kermit:~/work/publications/ans15s [master|…1]$ python ../zo/zo.py status
Traceback (most recent call last):
  File "../zo/zo.py", line 99, in <module>
    main()
  File "../zo/zo.py", line 94, in main
    status()
  File "../zo/zo.py", line 72, in status
    with open(path.join(getenv("HOME"), "refs", "refs.bib"), 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/gidden/refs/refs.bib'
```

**Comment by elliottbiondo** [comment]
fixed via f9d2761
